# Generated by Django 4.2.6 on 2023-12-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile-picture/')),
                ('phoneno', models.CharField(max_length=13, null=True)),
                ('education', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('expertise', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
